name: project2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  animations: ^2.0.7
  awesome_dialog: ^3.1.0
  badges: ^3.1.1
  countnumberbutton: ^0.0.7
  dropdown_button2: ^2.3.8
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  swipe_to: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
