// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEzezF-txwmyDImCynGRlN6HcbvgXmVas',
    appId: '1:595175608313:android:24886ce8139e68a1c57728',
    messagingSenderId: '595175608313',
    projectId: 'listy-96d4d',
    storageBucket: 'listy-96d4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyWEhzfaFI6hkpyUcvWsI8XfOeOMh0xp4',
    appId: '1:595175608313:ios:a18868d30f9eef8fc57728',
    messagingSenderId: '595175608313',
    projectId: 'listy-96d4d',
    storageBucket: 'listy-96d4d.appspot.com',
    androidClientId: '595175608313-0hed42nuiv0rlka67aj3sulr5j6ov7gj.apps.googleusercontent.com',
    iosClientId: '595175608313-u9u5f5f0farc8t1akdv2u1rccc68gjdj.apps.googleusercontent.com',
    iosBundleId: 'com.LamaAlyousef.shoppingList',
  );
}
